// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/25/2026, 3:03:03 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/wube/robocare-platform/client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/wube/robocare-platform/client/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/wube/robocare-platform/client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/wube/robocare-platform/client/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/wube/robocare-platform/client/app/plugins/**/*.{js,ts,mjs}","/home/wube/robocare-platform/client/app/composables/**/*.{js,ts,mjs}","/home/wube/robocare-platform/client/app/utils/**/*.{js,ts,mjs}","/home/wube/robocare-platform/client/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/wube/robocare-platform/client/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/wube/robocare-platform/client/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/wube/robocare-platform/client/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;